version: '3'

services:
    
    
    postgres:        
        image: postgres:13.3
        ports:
        - 5432:5432
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: scooby
            POSTGRES_DB: training
    
    customer:        
        build: customermsrestdatajpa
        ports:
        - 8484:8484

   
    